### ISSUE TITLE
Bind operator question

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [rob-brown/MonadEx#11]
Background 
----

I am trying this library and in specific I am trying the [Result Monad](https://hexdocs.pm/monadex/Monad.Result.html). The documentation mentions a function called [Result.bind](https://hexdocs.pm/monadex/Monad.Result.html#bind/2) and I have made it work with the following code snippet:

```
defmodule TestMonadex do
  use Monad.Operators

  import Monad.Result

  def p1(x) do
    x
    |> success()
    |> bind(&plus_1/1)
  end

  defp plus_1(n), do: n + 1
end
```

And so far so good.

Problem
----

The problem arises when I try to use the [bind operator](https://hexdocs.pm/monadex/Monad.Operators.html#~%3E%3E/2). According to the docs, this operator is the same thing as the `Result.bind` function. Following this logic, the following code snippet should work:

```
defmodule TestMonadex do
  use Monad.Operators

  import Monad.Result

  def p2(x) do
    success(x) ->> (&plus_1/1) # This does not compile!
  end

  defp plus_1(n), do: n + 1
end
```

Unfortunately, this is not compiling:

```
(SyntaxError) syntax error before: '>'

Stacktrace:
  │ (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

an expression is always required on the right side of ->. Please provide a value after ->
```

At this point I strongly believe I am not understanding something from the docs or from the library.

Question
---

What a I doing wrong?

**Comment by rob-brown** [comment]
The operator you're looking for is `~>>`. It's a tilde instead of a hyphen. Otherwise it's ambiguous with the `->` operator.

**Comment by Fl4m3Ph03n1x** [comment]
So the documentation is incorrect:

![Capture](https://user-images.githubusercontent.com/2980392/117325456-04442d80-ae91-11eb-8a3b-810fba8b4b17.PNG)

Or is it displayed differently in your browser?

**Comment by Fl4m3Ph03n1x** [comment]
After a closer look I have realized that my browser's zoom level, together with my font  made the docs harder to read. Everything is correct. 

Thank you for answer and I apologize for taking your time. Closing ticket.
