### ISSUE TITLE
CQRS Monads

### ISSUE THREAD

**Issue by henry-hz** [rob-brown/MonadEx#6]
Dear Rob,
I was wandering how to make a pure functional Monad to use with CQRS. The idea I found here: https://github.com/slashdotdash/eventsourced 
Every input command should generate an Event, and this event should be applied on the State. Maybe you could add in MonadEx or illuminate my way to implement it alone.

**Comment by rob-brown** [comment]
Are you wanting to implement CQRS or Event Sourcing? They are two different things, though they are frequently used together.

CQRS involves separating the read and write models of an application or system. Event sourcing involves recording facts then deriving state from those facts. 

From the link, I'm going to assume that you want to implement ES. You can do this with `Monad.Writer`. The writer monad has two values: the current state and a log. The log is effectively the same as an ES audit trail. The current state should be the same as if you applied all the facts to an initial state. If you want to guarantee this, you can make your own monad that derives the state each time. Here's how you could do that:

```elixir
defmodule BankAccount.Monad do
  use Monad.Behaviour

  defstruct initial: BankAccount.empty, facts: []

  def pure(state) do
    %__MODULE__{initial: state}
  end

  def bind(monad, fun) do
    new_monad = monad |> derive_state |> fun.()
    %__MODULE__{monad | facts: monad.facts ++ new_monad.facts}
  end

  def derive_state(monad) do
    reduce monad.facts, monad.initial, &apply_fact/2
  end

  defp apply_fact(state, fact) do
    # TODO: 
  end
end
```

I hope that helps.

**Comment by henry-hz** [comment]
Thanks for you fast feedback Rob,
yes you got what I meant, amazing idea.
best
